# Generated by Django 5.2.8 on 2025-12-05 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_date_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 5, 22, 51, 0, 107402)),
        ),
    ]
